dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
    - stage: build and release to github
      language: java
      jdk: oraclejdk8
      install: skip
      script: ./gradlew clean build -x test
      before_deploy:
        - git config --local user.name "Build Bot"
        - git config --local user.email "buildbot@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "applications/companybase/build/libs/companybase-1.0-SNAPSHOT.war"
          - "applications/employees-ms/build/libs/employees-ms-1.0-SNAPSHOT.jar"
          - "applications/clients-ms/build/libs/clients-ms-1.0-SNAPSHOT.jar"
          - - "applications/employeeprofile-ms/build/libs/employeeprofile-ms-1.0-SNAPSHOT.jar"
        skip_cleanup: true
    - stage: deploy to test
      language: java
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P applications/companybase/build/libs https://github.com/$GITHUB_USERNAME/companybase/releases/download/$RELEASE_TAG/companybase-1.0-SNAPSHOT.war
        - wget -P applications/employees-ms/build/libs https://github.com/$GITHUB_USERNAME/companybase/releases/download/$RELEASE_TAG/employees-ms-1.0-SNAPSHOT.jar
        - wget -P applications/clients-ms/build/libs https://github.com/$GITHUB_USERNAME/companybase/releases/download/$RELEASE_TAG/clients-ms-1.0-SNAPSHOT.jar
        - wget -P applications/employeeprofile-ms/build/libs https://github.com/$GITHUB_USERNAME/companybase/releases/download/$RELEASE_TAG/employeeprofile-ms-1.0-SNAPSHOT.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to company"
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: company
        skip_ssl_validation: true