server.port: 8084

spring:
  application:
    name: clientprofile-ms

  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/clientprofile?useSSL=false
    username: root