server.port: 8083

spring:
  application:
    name: employeeprofile-ms

  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/employeeprofile?useSSL=false
    username: root