spring:

  application:
    name: companybase

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  com.example.companybase.clientsui: DEBUG
  com.example.companybase.employeesui: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000